In [1]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [2]:
url='https://www.bankbazaar.com/reviews.html'
page=requests.get(url)
soup=BeautifulSoup(page.text,'html.parser')

In [23]:
review_text=[]
review_text_elem=soup.find_all(class_='text_here review-desc-more')
#review_text_elem
for item in review_text_elem:
    review_text.append(item.text)

res = [sub.replace('\n', '') for sub in review_text]

In [24]:
user_name=[]
user_name_elem=soup.find_all(class_='js-author-name')
for item in user_name_elem:
    user_name.append(item.text)
#print(user_name)

In [25]:
bank_name=[]
bank_name_elem=soup.find_all('div',attrs={'class':'review-bank-title'})
for item in bank_name_elem:
    bank_name.append(item.find('img').get('alt'))
#print(bank_name)    
#bank_name

In [26]:
final=[]
for text,user,bank in zip(res,user_name,bank_name):
    final.append({'Review_text':text,'User':user,'Bank':bank})
df=pd.DataFrame(final)
df

,Review_text,User,Bank
0,I have taken a...,F,review
1,I have taken a...,F PASHA,review
2,I have taken a...,FAYAZ,Capital First
3,Bajaj Allianz...,Satish,Bajaj Allianz Life
4,Its been more ...,SHAW,ICICI Bank
5,I have been us...,SUMIT,ICICI Bank
6,I am using ICI...,BISWA,ICICI Bank
7,I am using pay...,S SHARMA,review
8,I got the offe...,SUMIT,IndusInd Bank
9,I have applied...,BISWAJIT D,IndusInd Bank
10,I have taken ...,G MAURYA,LIC
11,I have taken a...,GAURAV,HDFC Life
12,I have HDFC Ba...,SURENDRA,HDFC Bank
13,I have taken ...,G,Bank of India
14,I didn't face ...,JEEVA,Citibank
15,Purchased my R...,MURTHY,RBL Bank
16,I am facing so...,VIJAYAKUMAR,Kotak
17,I am using BAN...,GAUR,Bank of Baroda
18,My friends tol...,VIJAYAKUMAR,HSBC Bank
19,I am using SBI...,GAU R,SBI Cards